#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MiRP - a microtubule RELION-based pipeline for cryo-EM image processing. 
MiRP v2 is designed to function with RELION v3.1, and is not compatible with earlier versions of RELION.
"""

__author__ = 'Alexander D. Cook & Joseph Atherton'
__license__ = 'GPLv3'
__version__ = '2.0'


import microtubules
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-i', '--in_parts', required=True, help='The input _data.star ifile from seam checking Class3D')
parser.add_argument('-o', '--o', required=True, help='The Output path/directory.')
parser.add_argument('--pf', required=True, help='The protofilament number microtubules in the _data.star file.')
parser.add_argument('--rise', required=True, help='The helical rise of the microtubules in the _data.star file.')
parser.add_argument('--conf', required=False, help='Cutoff for removing microtubules below a certain confidence in seam class assignment.')
parser.add_argument('-j', '--j', help='Multi-threading is not supported. This flag is required for function within RELION.')
args = parser.parse_args()

mts = microtubules.Microtubules(args.in_parts, args.o)

if args.conf:
    mts.vote_on_seam(args.conf, args.pf, args.rise)
else:
    mts.vote_on_seam(0, args.pf, args.rise)
